### ISSUE TITLE
Syncing Issue: Attribute Error

### ISSUE THREAD

**Issue by marcazo** [benmaddison/prngmgr#6]
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/brian/myprngmgr/prngmgr/prngmgr/management/commands/prngmgr-sync.py", line 8, in handle
    management.call_command('pdb_sync')
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django_peeringdb/management/commands/pdb_sync.py", line 87, in handle
    self.sync(tables, pk)
  File "/usr/local/lib/python2.7/dist-packages/django_peeringdb/management/commands/pdb_sync.py", line 94, in sync
    self.update_db(cls, self.get_objs(cls, pk=pk))
  File "/usr/local/lib/python2.7/dist-packages/django_peeringdb/management/commands/pdb_sync.py", line 173, in update_db
    self._sync(cls, row)
  File "/usr/local/lib/python2.7/dist-packages/django_peeringdb/management/commands/pdb_sync.py", line 142, in _sync
    sync.sync_obj(cls, row)
  File "/usr/local/lib/python2.7/dist-packages/django_peeringdb/sync.py", line 41, in sync_obj
    setattr(obj, field.name, value)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 521, in __set__
    setattr(value, field.attname, related_pk[index])
AttributeError: 'NoneType' object has no attribute 'netixlan_id'

**Comment by benmaddison** [comment]
@marcazo what `manage.py` command were you trying to run when you got this error?

**Comment by marcazo** [comment]
Hi @benmaddison this is the command that I was running: 
python manage.py prngmgr-sync

**Comment by benmaddison** [comment]
Fixed in peeringdb/django-peeringdb#10
